import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { example } from "../store/driver/driverSlice";
import { driverSelector } from "../store/driver/driverSelectors";
import { Column } from "../components/Layout/Column/ColumnAtom";
import { Row } from "../components/Layout/Row/RowAtom";
import { Container } from "../components/Layout/Container/ContainerAtom";

const Home: NextPage = () => {
  const { valueExample } = useSelector(driverSelector);
  const dispatch = useDispatch();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Row>
            <Column size={4}>
              <h1>Column 1</h1>
            </Column>
            <Column size={4}>
              <h1>Column 1</h1>
            </Column>
            <Column size={4}>
              <h1>Column 1</h1>
            </Column>
            <Column size={4}>
              <h1>Column 1</h1>
            </Column>
          </Row>
          <a onClick={() => dispatch(example())} className={styles.card}>
            <h2>REDUX TEST {valueExample}</h2>
          </a>
        </Container>
      </main>
    </div>
  );
};

export default Home;
