import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { setDrivers } from "../../store/driver/driverSlice";
import { driverSelector } from "../../store/driver/driverSelectors";
import { Column } from "../../components/Layout/Column/ColumnAtom";
import { Row } from "../../components/Layout/Row/RowAtom";
import {
  Container,
  ContainerFluid,
} from "../../components/Layout/Container/ContainerAtom";
import DriverCard from "../../components/Driver/Card/DriverCard";
import axios from "axios";
import { Driver } from "../../types/drivers";
import { useEffect } from "react";
import { Colors } from "../../types/variables";

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const drivers = await axios.get(`${process.env.PUBLIC_BASE_URL}/api/drivers`);
  return {
    props: {
      drivers: drivers.data,
    },
  };
};

const Home: NextPage<{ drivers: Driver[] }> = ({ drivers }) => {
  const { driversData } = useSelector(driverSelector);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(setDrivers(drivers));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ContainerFluid backgroundColor={Colors.Primary}>
          <Container>
            {driversData.length && (
              <Row>
                {driversData.map((driver: Driver, index: number) => (
                  <Column key={index} size={12} md={6} lg={3}>
                    <DriverCard data={driver} />
                  </Column>
                ))}
              </Row>
            )}
          </Container>
        </ContainerFluid>
      </main>
    </div>
  );
};

export default Home;
